version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gj_ai_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gj_ai_static:/data/static/
      - gj_ai_media:/data/media/

  django:
    image: gj_ai:4
    networks:
      - gj_ai_network
    volumes:
      - gj_ai_static:/home/practice/staticfiles/
      - gj_ai_media:/home/practice/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gj_ai_network
    volumes:
      - gj_ai_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: gj_ai_django
      MARIADB_USER: gj_ai_django
      MARIADB_PASSWORD: mypassword1234

networks:
  gj_ai_network:

volumes:
  gj_ai_static:
  gj_ai_media:
  gj_ai_mariadb: