version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - gj_ai_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gj_ai_static:/data/static/
      - gj_ai_media:/data/media/
      - gj_ai_log:/var/log/nginx/

  goaccess:
    image: allinurl/goaccess:1.5.1
    volumes:
      - gj_ai_log:/var/log/nginx/
    ports:
      - 7890:7890
    command: /var/log/nginx/gj_ai_access.log -o /var/log/nginx/report.html --log-format COMBINED --real-time-html

  django:
    image: gj_ai:5
    networks:
      - gj_ai_network
    volumes:
      - gj_ai_static:/home/practice/staticfiles/
      - gj_ai_media:/home/practice/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gj_ai_network
    volumes:
      - gj_ai_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD

    environment:
      MARIADB_DATABASE: gj_ai_django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  gj_ai_network:

volumes:
  gj_ai_static:
  gj_ai_media:
  gj_ai_mariadb:
  gj_ai_log:


secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true