version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gj_ai_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gj_ai_static:/data/static/
      - gj_ai_media:/data/media/

  django:
    image: gj_ai:5
    networks:
      - gj_ai_network
    volumes:
      - gj_ai_static:/home/practice/staticfiles/
      - gj_ai_media:/home/practice/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gj_ai_network
    volumes:
      - gj_ai_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD

    environment:
      MARIADB_DATABASE: gj_ai_django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  gj_ai_network:

volumes:
  gj_ai_static:
  gj_ai_media:
  gj_ai_mariadb:


secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true